allowBuilds:
  browser-tabs-lock: set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@clerk/clerk-js@6.15.0'
  - '@clerk/expo@3.4.0'
  - '@clerk/react@6.8.0'
  - '@clerk/shared@4.16.0'
